//  Copyright (c) 2019 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:projectid: microshed-testing
:page-layout: guide-multipane
:page-duration: 20 minutes
:page-releasedate: 2019-11-04
:page-guide-category: microprofile
:page-essential: true
:page-essential-order: 5
:page-description: Learn how to use MicroShed Testing to test a MicroProfile or Jakarta EE application.
:page-seo-title: Testing a MicroProfile or Jakarta EE application using MicroShed Testing with an Open Liberty docker container
:page-seo-description: A tutorial on how to develop tests for a MicroProfile microservice or a Jakarta EE application by using Open Liberty development mode provided by the Liberty Maven plugin.
:guide-author: Open Liberty
:page-tags: ['MicroProfile', 'Java EE', 'Jakarta EE', 'Testing', 'Docker']
:page-related-guides: ['rest-intro', 'docker', 'rest-client-java']
:page-permalink: /guides/{projectid}
:repo-description: Visit the https://openliberty.io/guides/{projectid}.html[website] for the rendered version of the guide.
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
= Testing a MicroProfile or Jakarta EE application

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Learn how to use MicroShed Testing to test a MicroProfile or Jakarta EE application.

== What you'll learn

You'll start with an existing REST application that runs on Open Liberty and use https://microshed.org/microshed-testing/[MicroShed Testing^] 
to write tests for the application that exercise the application inside of a Docker container.

Sometimes tests might pass in development and testing (dev/test) environments, but fail in production because the application is
running differently in production than it is in dev/test. Fortunately, you can minimize these parity issues between development and production
by testing your application in the same Docker container that you'll use in production.

=== What is Docker?

Docker is a tool that you can use to deploy and run applications with containers. You
can think of Docker as a virtual machine that runs various applications. However, unlike with a typical virtual
machine, you can run these applications simultaneously on a single system and independent of
one another.

Learn more about Docker on the https://www.docker.com/what-docker[official Docker website^].

To install Docker, follow the instructions in the https://docs.docker.com/engine/installation[official Docker documentation^].

[role="command"]
include::{common-includes}/gitclone.adoc[]

=== Try what you'll build

The `finish` directory in the root of this guide contains the finished application. Give it a try before you proceed.

First, review the [hotspot file=0]`PersonServiceIT` class to see what the tests look like:

PersonServiceIT.java
[source, java, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/test/java/io/openliberty/guides/testing/PersonServiceIT.java[]
----

To try out the application, go to the `finish` directory and run the following Maven 
goal to build the application and run the integration tests on an Open Liberty server in a container:
[role='command']
```
mvn verify
```

This command might take some time to run the first time because the dependencies and the Docker image for Open Liberty must download. If you 
run the same command again, it will be faster.

The previous example shows how you can run integration tests from a cold start. With Open Liberty development mode, you can use MicroShed Testing to run tests on
an already running Open Liberty server. Run the following Maven goal to start Open Liberty in development mode:

[role='command']
```
mvn liberty:dev
```

After the Open Liberty server starts and you see the `Press the Enter key to run tests on demand.` message, you can press the 
`enter/return` key to run the integration tests. After the tests finish, you can press the `enter/return` key to run the tests again, or you 
can make code changes to the application or tests. Development mode automatically
recompiles and updates any application or test code changes that you make.

After you are finished running tests, stop the Open Liberty server by typing `q` in the shell session where you ran the server, and then press the `enter/return` key. 

== Bootstrapping your application for testing

Navigate to the `start` directory to begin.

Start Open Liberty in development mode, which starts the Open Liberty server and listens 
for file changes:

[role="command"]
```
mvn liberty:dev
```

Wait for the `Press the Enter key to run tests on demand.` message, and then press the `enter/return` key to run the tests. You see that one test runs:

[role="no_copy"]
----
[INFO] Running integration tests...
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running io.openliberty.guides.testing.PersonServiceIT
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.024 s - in io.openliberty.guides.testing.PersonServiceIT
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO] Integration tests finished.
----

To begin bootstrapping, annotate the `src/test/java/io/openliberty/guides/testing/PersonServiceIT.java` class with the `@MicroShedTest` annotation. This annotation indicates that the test class uses MicroShed Testing.

[role="code_command hotspot file=0", subs="quotes"]
----
#Update the `PersonServiceIT` class.#
`src/test/java/io/openliberty/guides/testing/PersonServiceIT.java`
----
[role="edit_command_text"]
Import the [hotspot=importMicroShedTest file=0]`MicroShedTest` annotation and annotate the `PersonServiceIT` class with [hotspot=microShedTest file=0]`@MicroShedTest`.

PersonServiceIT.java
[source, java, linenums, role='code_column hide_tags=copyright']
----
include::hotspots/src/test/java/io/openliberty/guides/testing/PersonServiceIT.1.java[]
----
// if use PersonServiceIT.2.java, use following:
//[source, java, linenums, role='code_column hide_tags=copyright,importInject,importMPApp,importAssertNotNull,importSharedContainerConfig,sharedContainerConfig,inject,personSvc,mpApp,container,testCreatePerson']
//----
//include::hotspots/src/test/java/io/openliberty/guides/testing/PersonServiceIT.2.java[]
//----

Next, the `PersonServiceIT` class outlines some basic information that informs how MicroShed Testing starts the application runtime and at which URL path the application will be available:

[role="code_command hotspot file=1", subs="quotes"]
----
#Update the `PersonServiceIT` class.#
`src/test/java/io/openliberty/guides/testing/PersonServiceIT.java`
----
[role="edit_command_text"]
Import the [hotspot=importMPApp file=1]`ApplicationContainer` class and the [hotspot=importContainer file=1]`Container` annotation, create the [hotspot=mpApp file=1]`ApplicationContainer` application, and annotate the application with [hotspot=container file=1]`@Container`.

PersonServiceIT.java
[source, java, linenums, role='code_column hide_tags=copyright,importInject,importAssertNotNull,importSharedContainerConfig,sharedContainerConfig,inject,personSvc,testCreatePerson']
----
include::hotspots/src/test/java/io/openliberty/guides/testing/PersonServiceIT.2.java[]
----

The [hotspot=withAppContextRoot file=1]`withAppContextRoot(String)` method indicates the base path of the application. The app context root is the portion of the URL after the hostname and port. In this case, the application is deployed at the `\http://localhost:9080/guide-microshed-testing` URL, so the app context root is [hotspot=withAppContextRoot file=1]`/guide-microshed-testing`.

The [hotspot=withReadinessPath file=1]`withReadinessPath(String)` method indicates what path is polled by HTTP to determine application readiness. MicroShed Testing automatically starts the ApplicationContainer application and waits for it to be ready before the tests start running. In this case, you are using the default application readiness check at the http://localhost:9080/health/ready[http://localhost:9080/health/ready^] URL, which is enabled by the [hotspot=mpHealth file=2]`mpHealth` feature in our server.xml configuration file. When the readiness URL returns `HTTP 200`, the application is considered ready and the tests begin running.

server.xml
[source, xml, linenums, role='code_column']
----
include::finish/src/main/liberty/config/server.xml[]
----

Save your changes to the `PersonServiceIT` class and press the `enter/return` key in your console window to rerun the tests. You still see only one test running, but the output is different. Notice that MicroShed Testing is using a `hollow` configuration mode. This configuration mode means that MicroShed Testing is reusing an existing application runtime for the test, not starting up a new application instance each time you initiate a test run.

== Talking to your application with a REST client

With MicroShed Testing, applications are exercised in a black box fashion. Black box means the tests cannot access the application internals. Instead, the application is exercised from the outside, usually with HTTP requests. To simplify the HTTP interactions, inject a REST client into the tests.

[role="code_command hotspot file=0", subs="quotes"]
----
#Update the `PersonServiceIT` class.#
`src/test/java/io/openliberty/guides/testing/PersonServiceIT.java`
----
[role="edit_command_text"]
Import the [hotspot=importInject file=0]`org.microshed.testing.jaxrs.RESTClient` annotation, create a [hotspot=personSvc file=0]`PersonService` REST client, and annotate the REST client with [hotspot=inject file=0]`@RESTClient`.

PersonServiceIT.java
[source, java, linenums, role='code_column hide_tags=copyright,importAssertNotNull,importSharedContainerConfig,sharedContainerConfig,testCreatePerson']
----
include::hotspots/src/test/java/io/openliberty/guides/testing/PersonServiceIT.2.java[]
----

In this example, the [hotspot=personSvc file=0]`PersonService` injected type is the same [hotspot file=1]`io.openliberty.guides.testing.PersonService` class that is used in your application. However, the _instance_ that gets injected is a REST client proxy. So, if you call `personSvc.createPerson("Bob", 42)`, the REST client makes an HTTP POST request to the application that is running at http://localhost:9080/guide-microshed-testing/people[http://localhost:9080/guide-microshed-testing/people^], which triggers the corresponding Java method in the application.

PersonService.java
[source, java, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/main/java/io/openliberty/guides/testing/PersonService.java[]
----


== Writing your first test

Now that the setup is complete, you can write your first test case. Start by testing the basic "create person" use case for your REST-based application. To test this use case, use the REST client that's injected by MicroShed Testing to make the HTTP POST request to the application and read the response.

[role="code_command hotspot file=0", subs="quotes"]
----
#Update the `PersonServiceIT` class.#
`src/test/java/io/openliberty/guides/testing/PersonServiceIT.java`
----
[role="edit_command_text"]
Import the [hotspot=importAssertNotNull file=0]`assertNotNull` static method and write the test logic in the [hotspot=testCreatePerson file=0]`testCreatePerson()` method.

PersonServiceIT.java
[source, java, linenums, role='code_column hide_tags=copyright,importSharedContainerConfig,sharedContainerConfig']
----
include::hotspots/src/test/java/io/openliberty/guides/testing/PersonServiceIT.2.java[]
----

Save the changes. Then, press the `enter/return` key in your console window to run the test. You see that the test ran again and exercised the REST endpoint of your application, including the response of your application's endpoint:

[role="no_copy"]
----
INFO org.microshed.testing.jaxrs.RestClientBuilder  - Building rest client for class io.openliberty.guides.testing.PersonService with base path: http://localhost:9080/guide-microshed-testing/ and providers: [class org.microshed.testing.jaxrs.JsonBProvider]
INFO org.microshed.testing.jaxrs.JsonBProvider  - Response from server: 1809686877352335426
----

Next, add more tests.

[role="code_command hotspot file=1", subs="quotes"]
----
#Replace the `PersonServiceIT` class.#
`src/test/java/io/openliberty/guides/testing/PersonServiceIT.java`
----

PersonServiceIT.java
[source, java, linenums, role='code_column hide_tags=copyright']
----
include::hotspots/src/test/java/io/openliberty/guides/testing/PersonServiceIT.3.java[]
----

The following tests are added: [hotspot=testMinSizeName file=1]`testMinSizeName()`, [hotspot=testMinAge file=1]`testMinAge()`, [hotspot=testGetPerson file=1]`testGetPerson()`, [hotspot=testGetAllPeople file=1]`testGetAllPeople()`, and [hotspot=testUpdateAge file=1]`testUpdateAge()`.


Save the changes, and  press the `enter/return` key in your console window to run the tests.

== Testing outside of development mode

Running tests in development mode is convenient for local development, but it can be tedious to test against a running Open Liberty server in non-development scenarios such as CI/CD pipelines. For this reason, MicroShed Testing can start and stop the application runtime before and after the tests are run. This process is primarily accomplished by using Docker and Testcontainers.

To test outside of development mode, exit development mode by typing `q` in the shell session where you ran the server, and then press the `enter/return` key.

Next, use the following Maven goal to run the tests from a cold start:
[role='command']
```
mvn verify
```

Running tests from a cold start takes a little longer than running tests from development mode because the application runtime needs to start each time. However, tests that are run from a cold start use a clean instance on each run to ensure consistent results. These tests also automatically hook into existing build pipelines that are set up to run the `integration-test` phase.

== Sharing configuration across multiple classes

Typically, projects have multiple test classes that all use the same type of application deployment. For these cases, it is useful to reuse an existing configuration and application lifecycle across multiple test classes.

First, create another test class.

[role="code_command hotspot file=0", subs="quotes"]
----
#Create the `ErrorPathIT` class.#
`src/test/java/io/openliberty/guides/testing/ErrorPathIT.java`
----

ErrorPathIT.java
[source, java, linenums, role='code_column hide_tags=copyright,importSharedContainerConfig,sharedContainerConfig']
----
include::hotspots/src/test/java/io/openliberty/guides/testing/ErrorPathIT.java[]
----

The `ErrorPathIT` test class has the same [hotspot=container file=0]`@Container` configuration and [hotspot=personSvc file=0]`PersonService` REST client as the `PersonServiceIT` class.

Now, run the tests again outside of development mode:
[role='command']
```
mvn verify
```

Notice that tests for both the `PersonServiceIT` and `ErrorPathIT` classes run, but a new server starts for each test class, resulting in a longer test runtime.

To solve this issue, common configuration can be placed in a class that implements `SharedContainerConfiguration`.
  
[role="code_command hotspot file=1", subs="quotes"]
----
#Create the `AppDeploymentConfig` class.#
`src/test/java/io/openliberty/guides/testing/AppDeploymentConfig.java`
----

AppDeploymentConfig.java
[source, java, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/test/java/io/openliberty/guides/testing/AppDeploymentConfig.java[]
----

After the common configuration is created, the test classes can be updated to reference this shared configuration.

Remove the container code from the `PersonServiceIT` class.
[role="code_command hotspot file=2", subs="quotes"]
----
#Update the `PersonServiceIT` class.#
`src/test/java/io/openliberty/guides/testing/PersonServiceIT.java`
----
[role="edit_command_text"]
Remove [hotspot=importMPApp hotspot=importContainer file=2]`import` statements and the [hotspot=container hotspot=mpApp file=2]`ApplicationContainer app` field.

PersonServiceIT.java
[source, java, linenums, role='code_column hide_tags=copyright']
----
include::hotspots/src/test/java/io/openliberty/guides/testing/PersonServiceIT.2.java[]
----

Annotate the `PersonServiceIT` class with the `@SharedContainerConfiguration` annotation that references the `AppDeploymentConfig` shared configuration class.
[role="code_command hotspot file=3", subs="quotes"]
----
#Update the `PersonServiceIT` class.#
`src/test/java/io/openliberty/guides/testing/PersonServiceIT.java`
----
[role="edit_command_text"]
Import the [hotspot=importSharedContainerConfig file=3]`SharedContainerConfig` annotation and annotate the `PersonServiceIT` class with [hotspot=sharedContainerConfig file=3]`@SharedContainerConfig`. 

PersonServiceIT.java
[source, java, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/test/java/io/openliberty/guides/testing/PersonServiceIT.java[]
----

Similarly, update the `ErrorPathIT` class to remove the container code.
[role="code_command hotspot file=4", subs="quotes"]
----
#Update the `ErrorPathIT` class.#
`src/test/java/io/openliberty/guides/testing/ErrorPathIT.java`
----
[role="edit_command_text"]
Remove [hotspot=importMPApp hotspot=importContainer file=4]`import` statements and the [hotspot=container hotspot=mpApp file=4]`ApplicationContainer app` field

ErrorPathIT.java
[source, java, linenums, role='code_column hide_tags=copyright']
----
include::hotspots/src/test/java/io/openliberty/guides/testing/ErrorPathIT.java[]
----

Annotate the `ErrorPathIT` class with the `@SharedContainerConfiguration` annotation.
[role="code_command hotspot file=5", subs="quotes"]
----
#Update the `ErrorPathIT` class.#
`src/test/java/io/openliberty/guides/testing/ErrorPathIT.java`
----
[role="edit_command_text"]
Import the [hotspot=importSharedContainerConfig file=5]`SharedContainerConfig` annotation and annotate the `ErrorPathIT` class with [hotspot=sharedContainerConfig file=5]`@SharedContainerConfig`. 

ErrorPathIT.java
[source, java, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/test/java/io/openliberty/guides/testing/ErrorPathIT.java[]
----

If you rerun the tests now, they run in about half the time because the same server instance is being used for both test classes:
[role='command']
```
mvn verify
```

== Great work! You're done!

You developed automated tests for a REST service in Open Liberty by using MicroShed Testing and Open Liberty development mode.

== Related Links

Learn more about MicroShed Testing.

https://microshed.org/microshed-testing/[View the MicroShed Testing website^]

include::{common-includes}/attribution.adoc[subs="attributes"]
